config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  root to: 'eoliennes#index'
  resources :eoliennes, only: [ :index, :show ] do
    resources :bookings, only: [ :new, :create ]
  end
  get '/valeurs', to: 'pages#valeurs'
  get '/fonctionnement', to: 'pages#fonctionnement'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :eolienne
end

app/models/eolienne.rb
class Eolienne < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  has_many :eoliennes, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:eolienne_id])
  end
end

app/controllers/eoliennes_controller.rb
class EoliennesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @eoliennes = Eolienne.all
  end

  def show
    @eolienne = Eolienne.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def valeurs
  end

  def fonctionnement
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @eoliennes = @user.eoliennes
    @bookings = @user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/eoliennes/index.html.erb
<div class="my-container">
  <div class="my-container">
    <div class="row">
      <div class="col-lg-6 col-sm-12 left-box">
        <div class="banner-content">
          <h1>Connectez-vous au vent!</h1>
          <h3>L'éolienne de 600W prête à l'emploi.</h3>
          <h3>sans <span id='banner-typed-text'></span></h3>
        </div>
        <div class="description">
          <div class="description-content">
            <div class="description-text">
              <h5>Branchez</h5>
              <p>sur une prise 220V</p>
            </div>
            <i class="fas fa-plug"></i>
          </div>
          <div class="description-content">
            <div class="description-text">
              <h5>Customisez</h5>
              <p>selon vos envies</p>
            </div>
            <i class="fas fa-paint-roller"></i>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-sm-12 right-box">
        <div class='overflow-wrap'>
          <div class='video' style="overflow:hidden">
            <%= video_tag "wheat.mp4", controls: false, autoplay: true, muted:
            true, loop: true, id: 'bgvideobg', class: 'bkrg-video', type: "video/mp4", crop: :fill, poster: 'wheat.jpg' %>
          </div>
        </div>
      </div>
      <div class="no-overflow img-fluid" style="overflow:visible">
        <%= image_tag "eol-banner.png", class: "image-eolienne img-fluid" %>
      </div>
  </div>

  <div class="my-container">
    <div class="row">
      <div class="col-12 third-box">
        <a href="#eoliennes" class="whole-pack">
          <i class="fas fa-chevron-down arrow bounce"></i>
          <p>Découvrez nos produits</p>
        </a>
      </div>
    </div>
  </div>

  <div class="product-container" id="eoliennes">
    <div class="row">
      <div class="col">
        <div class='product-header'><h2>Choisissez votre pack</h2></div>
      </div>
    </div>



    <div class="row">
      <div class="col-12">
          <div class='product-box'>
            <% @eoliennes.each do |eolienne| %>
              <%= link_to eolienne_path(eolienne) do %>
                <div class="slide-in">
                  <div class="box">
                    <span class="original">
                      <%= image_tag(eolienne.photo, height: 'auto', width: '270', class: 'img-card img-fluid') %>
                    </span>
                    <div class="overlay">
                      <h2><%= eolienne.name %></h2>
                      <h5><%= eolienne.description %></h5>
                      <h6><%= eolienne.price %>€</h6>
                    </div>
                  </div>
                </div>
                <h2 class='card-title'><%= eolienne.name %></h2>
              <% end %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/eoliennes/show.html.erb
<div class="my-container">
  <div class="my-container">
    <div class="row">
      <div class="col-lg-6 col-sm-12 left-eol">
        <div class="eolienne-box img-fluid">
          <%= image_tag(@eolienne.photo, class: 'thissticky img-fluid') %>
        </div>
      </div>
      <div class="col-lg-6 col-sm-12 right-eol">
        <div class="eolienne-title">
          <h1><%= @eolienne.name %> - <%= @eolienne.price %>€</h1>
        </div>
        <div class="eolienne-description">
          <div class="eol-content">
            <div class="eol-text">
              <div class='small-title'><h5>Le saviez-vous ?</h5></div>
              <p>
                La puissance d'une éolienne (en kW, kilowatts) mesure sa 
                capacité de production d'électricité. C'est une caractéristique
                technique qui ne dépend que de l’éolienne en elle-même, et
                <strong>non de l'endroit où elle est posée</strong>. Autrement
                dit, une éolienne de 1 kW de puissance ne pourra pas fournir
                plus d’énergie en 1 heure qu\'1 kWh même si elle est alimentée
                en vent par un ouragan. Elle a l'avantage de fonctionner <strong>
                sans avoir besoin de vent fort</strong>. Elle fonctionne également
                sur <strong>360°</strong>, c’est-à-dire quelque soit l’axe du vent.
              </p>
            </div>
          </div>
          <div class="eol-content">
            <div class="eol-text">
              <div class='small-title'><h5>Fiche technique</h5></div>
              <div class="eol-list">
                <ul class='col-12 list-1'>
                  <li><strong>Hauteur : </strong><%= @eolienne.height %></li>
                  <li><strong>Largeur : </strong><%= @eolienne.width %></li>
                  <li><strong>Poids : </strong><%= @eolienne.weight %></li>
                  <li><strong>Taille de voile : </strong><%= @eolienne.size %></li>
                  <li><strong>Puissance : </strong><%= @eolienne.engine %></li>
                </ul>
                <ul class='col-12 list-2'>
                  <li><strong>Pied : </strong><%= @eolienne.base %></li>
                  <li><strong> Matériaux : </strong><%= @eolienne.product %></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="eol-content">
            <div class="eol-text">
              <div class='small-title'><h5>Capacité de production</h5></div>
              <p>Il faut un <strong>minimum de 15km/h</strong> de vent pour que l'éolienne produise du 220v.
                L'éolienne produit maximum 600w.
                Et elle produit le courant pour le frigo, les éclairages, la télé, les appareils de recharge....
                Comme avec les capteurs solaires, si pas de soleil pas de production. Donc pas de vent = pas de production.
                Pour résumer, une éolienne peut produire <strong>1/3 de la consommation annuelle d'une maison</strong>.
              </p>
              <h5>L’avantage de l’éolienne : le stockage</h5>
                <p>
                  L’avantage de l’éolienne, c’est que l’électricité que vous
                  produisez peut être <strong>stockée</strong>. En effet, vous n’utilisez pas
                  toujours l’électricité au moment exact où elle est produite
                  par votre éolienne domestique. Votre petit éolien est relié à
                  des batteries qui peuvent seulement <strong>stocker et redistribuer du
                  courant continu</strong>. Un régulateur avec redresseur est ainsi placé
                  entre l’éolienne domestique et les batteries. Un onduleur est
                  installé après les batteries et avant votre maison pour
                  <strong>transformer le courant continu en courant alternatif</strong>.
                </p>
            </div>
          </div>
        </div>
        <br>
        <div class="button-location">
          <button class="button-eol">acheter</button>
          <button class="button-eol">customiser</button>
        </div>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Up2Wind</title>
    <%= favicon_link_tag asset_path('logo_UP2WINDgreen.svg') %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/fonctionnement.html.erb
<div class="my-container">
  <div class="value-container">
    <div class="row">
      <div class="col-lg-6 right-fonct">
        <div class="img-fluid">
           <%= cl_image_tag "https://res.cloudinary.com/dd6miiair/image/upload/v1585311450/eol-out_qhrh9k.jpg", class: "img-fonct img-fluid" %>
        </div>
      </div>
      <div class="col-lg-6 left-fonct">
        <div class="eolienne-description">
          <div class='link-anim'><h2>Le fonctionnement</h2></div>
          <div class="eol-content-value">
            <div class="eol-text">
              <p>
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu
                fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id
                est laborum."
              </p>
            </div>
            <div class="eol-text">
              <p>
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu."
              </p>
            </div>
          </div>
        </div>
      </div>
  </div>

app/views/pages/valeurs.html.erb
<div class="my-container">
  <div class="value-container">
    <div class="row">
      <div class="col-lg-6 left-value-1">
        <div class="eolienne-description">
          <div class='link-anim'><h2>Nos valeurs</h2></div>
          <div class="eol-content-value">
            <div class="eol-text">
              <h3>Le projet associatif</h3>
              <p>
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu
                fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id
                est laborum."
              </p>
            </div>
            <div class="eol-text">
              <h3>Une volonté éco-responsable</h3>
              <p>
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu
                fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id
                est laborum."
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 right-value-1">
        <div class="img-fluid">
           <%= cl_image_tag "https://res.cloudinary.com/dd6miiair/image/upload/v1585311452/eol-winter_yd1vaf.jpg", class: "img-values img-fluid" %>
        </div>
      </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1> <%= image_tag "logo_UP2WINDgreen.svg" %>
    UP2WIND</h1>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="all-nav">
        <li class="nav-connect">
          <%= link_to "Qui sommes-nous?", valeurs_path, class: "nav-link link05" %>
        </li>
        <li class="nav-connect">
          <%= link_to "Comment ça marche?", fonctionnement_path, class: "nav-link link05" %>
        </li>
        <li class="nav-connect">
          <%= link_to "Nos produits", eoliennes_path(anchor: 'eoliennes'), class: "nav-link link05" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-connected nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatar-default.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, width: '40px', height: '40px' %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Mes commandes", "#", class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item " %>
            </div>
          </li>
        <% else %>
          <li class="nav-connect-sans">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link button-eol-navbar" %>
          </li>
        <% end %>
      </div>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1 >Bonjour <strong><%= @user.first_name %></strong>,</h1>
<p>Bienvenue sur ton profil.</p>

<div class='container'>
  <div class="row">
    <div class="col">
        <div class='my-profile'>
          <div class="details">
            <h3>Détails personnnels</h3>
            <p><%= current_user.first_name %></p>
            <p><%= current_user.last_name %></p>
            <p><%= current_user.email %></p>
          </div>
          <div class="livraison">
          <h3>Adresse de livraison</h3>

          </div>
          <div class="facturation">

          <h3>Adresse de facturation</h3>
          </div>
          <div class="paiement">
          <h3>Mode de paiement</h3>

          </div>
          <div class="commandes">
          <h3>Voir mes commandes</h3>

          </div>
        </div>
    </div>
  </div>

</div>